// Unity build para Arduino IDE: compila modulos en subcarpetas.
#include "core/WeatherData.cpp"
#include "core/SensorManager.cpp"
#include "core/TaskManager.cpp"
#include "utils/I2CBus.cpp"
#include "sensors/BMP085.cpp"
#include "sensors/BMP180Sensor.cpp"
#include "sensors/DHT11Sensor.cpp"
#include "display/Max7219Display.cpp"
#include "display/DisplayManager.cpp"
#include "display/oled/OLEDDisplay.cpp"
#include "display/oled/OLEDDisplayModule.cpp"
#include "network/StationWiFi.cpp"
#include "network/WebServerManager.cpp"
#include "network/OTAManager.cpp"
#include "network/SerialDiagnostics.cpp"
#include "network/NtpTime.cpp"
