; Indoor — display MQTT (ESP8266 NodeMCU / ideaspark OLED)
; Compilar desde esta carpeta: pio run

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 80000000L

build_flags =
	-DPIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
	-D MQTT_MAX_PACKET_SIZE=512

lib_deps =
	tzapu/WiFiManager@^2.0.17
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^6.21.5
	arduino-libraries/NTPClient@^3.2.1
	adafruit/Adafruit GFX Library@^1.11.9
	adafruit/Adafruit ST7735 and ST7789 Library@^1.10.4
	adafruit/Adafruit SSD1306@^2.5.9
